# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtsUJefkAU0CyBGzKv8RIbB2oy39-MKU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('train.txt',sep= ';',header = None, names= ['text', 'emotion'])

df.head()

df.isnull().sum

"""**Embadding**"""

unique_emotions = df['emotion'].unique()
unique_emotions

emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i = i+1

df['emotion'] = df['emotion'].map(emotion_numbers)



"""***Text Preprocessing Technique***

**Convert Text into Lower form**
"""

df['text'] = df['text'].apply(lambda x: x.lower())

"""**2. Remove Punctuations**"""

# , @, $,
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('', '', string.punctuation))

df['text'] = df['text'].apply(remove_punc)

"""**3. Remove numbers**"""

def remove_numbers(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new+i
  return new

df['text'] = df['text'].apply(remove_numbers)

"""4. remove URL and LINks"""

#........

"""**5. Remove HTML Tags**"""

#......

"""**6. Removr Emojis & Special Character**"""

def remove_emojis(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new = new+i
  return new

df['text'] = df['text'].apply(remove_emojis)

"""**7. Remove stopWords **"""

# "is", "for", "was", "and", "in"  etc

import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')  # used for tokenization

stop_words = set(stopwords.words('english'))

df.loc[1]['text']

from nltk.corpus.reader.ycoe import wordpunct_tokenize
def remove(txt):
  words = wordpunct_tokenize(txt)
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return " ".join(cleaned)

df['text'] = df['text'].apply(remove)

df.loc[1]['text']

df.head()

"""***Feature Extraction / Vectorization***

1. One hot Encoding
2. Bag of Words
3. TF - IDF
4. Word2vec
5. BERT/Transformers
"""

# Vectorization -> convert text into numbers is called ...

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

bow_vectorizer = CountVectorizer() # bow -> bag of words

X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

pred_bow = nb_model.predict(X_test_bow)

print(accuracy_score(y_test, pred_bow))

pred_bow

tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf, y_train)

y_pred = nb2_model.predict(X_test_tfidf)

print(accuracy_score(y_test, y_pred))



from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression()
logistic_model.fit(X_train_tfidf, y_train)

log_pred = logistic_model.predict(X_test_tfidf)

print(accuracy_score(y_test, log_pred))



import joblib
joblib.dump(nb_model, 'nb_model.pkl')

model = joblib.load('nb_model.pkl')
model

